### ISSUE TITLE
Filters (integrated and external)

### ISSUE THREAD

**Issue by frabera** [y-taka-23/wasm-pandoc#2]
Is it technically possible to compile it enabling citeproc (which is integrated)? And external filters (like pandoc-crossref)?

Impressive work, by the way.

**Comment by y-taka-23** [comment]
@frabera Thanks for your comment! But unfortunately, both types of filters cannot work in this wasm-pandoc PoC. This repository depends on a little-bit-old Pandoc (v2.9.2.1), which is caused by Asterius compiler's dependencies, thus the citeproc filter is not integrated yet. Speaking of pandoc-crossref, a wasm file runs on an RTS wrapper, so it cannot access external filters provided as local files.
